apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: postgres
  description: postgres
  annotations:
    backstage.io/kubernetes-id: test
    backstage.io/techdocs-ref: test
    backstage.io/techdocs-entity: test
  tags:
    - postgres

  links:
    - url: https://admin.example-org.com
      title: Admin Dashboard
      icon: dashboard
      type: admin-dashboard
    - url: https://metrics.example-org.com
      title: metrics
      icon: analytics
      type: metrics-dashboard
    - url: https://logs.example-org.com
      title: logs
      icon: assignment
      type: logs-dashboard  
spec:
  type: service
  lifecycle: production
  owner: users-team
  system: public-websites
nav:
  - Home: index.md
  - Subpage: sub-page.md
  - 'Code Sample': code/code-sample.md
  - Extensions: extensions.md
plugins:
  - techdocs-core
